source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'bcrypt'
gem 'jquery-rails'
gem 'sass-rails'
gem 'font-awesome-sass'
gem 'awesome_print'
gem 'responders'

#added by brenda
gem 'activesupport'

group :development, :test do
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rspec-rails'
end

group :development do
  gem 'web-console', '~> 2.0'
end

